### ISSUE TITLE
Make AI:MMO use semver instead of versioneer

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1130]
## Task Description
Currently, AI:MMO uses versioneer as well as version.txt. The other projects use semver, so we want to make AI:MMO use that too to make our projects consistent as well as making it easier to deploy to dev.

## Acceptance Criteria
- [x] The version is updated using semantic PR titles
- [x] If merged to development, the version should be appended with .b{travis_build_number}
- [x] If pushed to the dev server, the version should be appended with .dev{travid_build_number}
- [ ] When merged into master, the version should be the version only.
- [ ] The `/versions/` URL in appengine should point to AI:MMO's new version.
