### ISSUE TITLE
Center avatar on load and "uncenter" on pan

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#1189]
## Task Description

The description is the task title. It is worth noting that there will be no way to recenter your avatar (apart from refreshing the page) until aimmo#1190 is done.

## Acceptance Criteria

- [x] When the game page loads up, the camera should be centred on the user's avatar. 
This can be done with `camera.setTarget(your_avatars_mesh)`

- [x] When you pan away from your avatar, the camera should unset the avatar's mesh so the user appears to be dragging the map (i.e. the current behaviour)

- [x] The state of whether or not you are centred on the avatar should be kept in the redux game state

## Copywrite Requirements

None

## Analytics Requirements

None
