### ISSUE TITLE
Implement backpack concept

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1279]
## Task Description
We want to implement the concept of a backpack for the avatar. The backpack will be a list which will hold the artefact objects that the avatar has picked up. The backpack will also need to have a maximum carry capacity.

## Acceptance Criteria
- [x] `number_of_artefacts` replaced with `backpack`
- [x] returns a list of Artefact objects
- [x] backpack is added to worker API
- [x] backpack is serialised
- [x] backpack has a maximum size a.k.a. maximum carry capacity
- [x] `ArtefactEffect` is changed to add artefact to backpack.
- [x] `PickupAction` is changed so the artefact is picked up if there is still space in the backpack
- [x] A log (or something) needs to be outputted if the Pickup Action fails because of the above condition
