### ISSUE TITLE
Have 2 types of Artefacts

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1280]
## Task Description
We want to have two different types of Artefacts in the game, of two different colours.
For now, the effect will be the same.

## Acceptance Criteria
- [ ] The two colours have been chosen.
- [ ] Change current `Artefact` to `YellowArtefact` (depending on the colour)
- [ ] Create second XXArtefact class.
- [ ] Have them show and appear on the front end.
- [ ] Change `PickupAction` to check for both types.
