### ISSUE TITLE
Implement Pyodide to have it run locally

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1310]
## Task Description
As a basis for this epic, we need to add code to have Pyodide run locally and also to load Python files asynchronously as well as pre-load the worker libraries.

This implementation should also include the handling of the edge cases mentioned in #1309.

## Acceptance Criteria
- [x] Pyodide runs locally
- [x] Files and libraries are loaded successfully
- [x] Edge cases are handled
- [x] Appropriate location for this code has been respected
- [ ] Testing
