### ISSUE TITLE
Create a package with the avatar api

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#1326]
## Task Description

Pyodide can download pip packages from PyPi, which is what we will use in order for the Pyodide workers to access the api

## Acceptance Criteria

- [ ] package with just the API loaded into codeforlife's PyPi account
- [ ] CI/CD process for this package setup
- [ ] uses same semver as the rest of aimmo

## Copywrite Requirements

- [ ] Check package name

## Analytics Requirements

- [ ] Perhaps check PyPi download count?
