### ISSUE TITLE
Have ability to create different worker API sets

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1360]
## Task Description
We want to be able to have a way to generate different worker API sets.
This will be needed in order to create different Worksheet model entries which will each have their own API set based on the worksheets created by Rebecca.

The aimmo_avatar_api package will also need to be built depending on this API set.

## Acceptance Criteria
- [x] Functionality to create an API set implemented
- [x] Choosing the API is clean and easy to do.
- [x] aimmo_avatar_api package reacts to API set.

**Comment by faucomte97** [comment]
Update: I've started the work to be able to have different API sets.
This has proved quite challenging so far because the following classes need to change depending on the worksheet/API set:
- AvatarState
- AvatarWrapper
- WorldMap
- Cell (maybe)

For the moment, I've only dealt with a POC to try having an API set for Worksheet 1 (a basic API set) and one for Worksheet 2 (the basic set + backpack).
Because it seems like a previous worksheet's API set would be available to the next, I've tried this POC using polymorphism / inheritance. I've therefore created a `BasicAvatarState` and a `BasicAvatarWrapper`, and created one extension for each of those classes to represent an API set for Worksheet 2.

At the moment, the way the game decides which API set to load is hardcoded. This is because the parameter will need to come from the Worksheet model associated to the Game - as such this is now waiting on #1359.

At the moment, the idea is to pass in only the Worksheet ID or name, which will then load the appropriate API set class for each of the aforementioned classes. This might get quite messy so we probably want to consider using an appropriate data structure to store which Worksheet relates to which API set, and which API set contains which functions / attributes for which classes.

The original plan was to have the 'API set' as a Worksheet model field, but I could not think of an efficient or easy enough way to hold that kind of data within a model, as it would need to store, as described above, which classes need to be extended, and with what functions / attributes.

It's also worthy to note that this approach does not require the `aimmo_avatar_api` package to react to which worksheet. Instead the package will always get fed in advance the necessary API set.
The frontend, however, in `pyodideRunner`, needs to know which worksheet is loaded to be able to generate the correct AvatarState.

Needs further discussion.

**Comment by mrniket** [comment]
So after having talked to @faucomte97, the plan is:

From the Django server in the `/games/` API, we will give the **game-creator** the worksheet id for each game. When a game is created, the game-creator will put this id as an environment variable for the game container.

Now that `aimmo-game` has access to the worksheet id, it can modify the game for each worksheet. The things we have identified as needing changing per worksheet:

`MapUpdaters`s applied (what interactables are on the board and how that are spawned will be part of this)
The `AvatarState` needs to show/hide different properties
`WorldMap` methods
The starter code
The era
Actions available to use

#### MapUpdaters

The `MapUpater`s all inherit from `_MapUpdater` so we can just store the classes in a list that we can provide per worksheet and then iterate over:

```python
for MapUpdater in self._map_updaters:
            MapUpdater().update(self.game_state.world_map, context=context)
```

#### AvatarState

Given that `AvatarState` is just a class holding a bunch of properties, we could just send the correct JSON based on the worksheet we are on to the game_frontend and convert them into an object like so:

```python
avatar_state = namedtuple("AvatarState", avatar_state_dict.keys())(*avatar_state_dict.values())
```

#### WorldMap methods

The base `WorldMap` is always the same, we can create a base `WorldMap` and then assign a set of extra methods (for example `scan_nearby()`) for each worksheet

```python
world_map = WorldMap(...)
world_map.scan_nearby = scan_nearby
```

#### Era

This can be passed via the game state updates

#### Actions available to use

This could either be imported conditionally based on the worksheet id in the **game_frontend** or invalid actions per worksheet can be rejected by `aimmo-game`

I think that covers everything 🤞
