### ISSUE TITLE
Create Worksheet model

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1361]
## Task Description
A Worksheet model needs to be added.

Specs:
- Each Game is linked to only 1 Worksheet, but a Worksheet can be linked to many Games (1 to * relationship)

Fields:
- ID
- Name
- API set (which functions and attributes out of the avatar API the Worksheet gives access to)
- Era (the time period the Worksheet is set in, used for the Asset Pack)
- Starter code
- Interactable spawner set

All fields are compulsory.

## Acceptance Criteria
- [x] Worksheet model has been created
- [x] Has all fields mentioned above
- [x] Model has been added to admin pages for simple visualisation

**Comment by faucomte97** [comment]
Update:

- The API set field might not be needed. The work I've done on the API set task makes it so that the API set is decided depending on the worksheet's ID or Name (to be decided). For now this has been done like so as no easy / clear way to store a 'API set' (which would contain functions and attributes specific to AvatarWrapper, AvatarState and WorldMap) has been identified.

- The Interactacle Spawner hasn't been put in yet as the front end / specific interactables task has not been discovered so it is unsure for how what structure this Spanwer would have. It can be added to the model later on.
