### ISSUE TITLE
Make Game depend on a Worksheet on creation

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1362]
## Task Description
A Game needs to be linked to a Worksheet, meaning the model needs to be updated.
The aimmo-game simulation needs to be updated to receive the data about the Worksheet from the Game so that the Game is initialised correctly, including the era, starter code, etc...
Until the UI for creating the game is decided and implemented, the worksheet could be hardcoded in perhaps, to provide the infrastructure for it already.

## Acceptance Criteria
- [x] Game model has a Worksheet PK.
- [x] aimmo-game simulation reads data from Worksheet and creates game accordingly
- [x] Worksheet is hardcoded until UI is coded (otherwise Worksheet is initialised through UI)

**Comment by mrniket** [comment]
worksheet is hardcoded to worksheet 1 for new games
