### ISSUE TITLE
Deal with 'legacy' games

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1365]
## Task Description
Games will no longer be created in the same way, as such any existing Games created before that will not be usable anymore.

To fix this, the Games will need to be linked to a Class and a Worksheet.

Research for this will need to be done, but an idea would be that the 'legacy' Games would be stored in a separate table, where the user would be prompted to assign them to a Class and Worksheet, after which they would rejoin the usable Games table.

## Acceptance Criteria
- [ ] Research UX/UI and flow for this task
- [ ] Make legacy Games non-startable until changes are made
- [ ] Implement option to assign Class and Worksheet to legacy Games

**Comment by mrniket** [comment]
Games without a worksheet are now tied to worksheet 2 by default. However, the case where a game does not have a class assigned to it still needs to be handled.

**Comment by mrniket** [comment]
To be done in #1227
