### ISSUE TITLE
Add Class field to Game

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1378]
## Task Description
Add a Class field to the Game model. This should be a foreign key to the Class model in the common package created in [1226](https://app.zenhub.com/workspaces/code-for-life-development-56f2afba6e54555c586f6db3/issues/ocadotechnology/codeforlife-portal/1226).

N.B.: To cater for existing games, this FK should be nullable.

## Acceptance Criteria
- [ ] Common package has been added to requirements and installed apps.
- [ ] Game model has FK to Class model from common package.
- [ ] Game creation form **excludes** Class field.
- [ ] Game admin page either doesn't allow to edit the Class field, or allows to change it only through the use of a lookup, and not a dropdown. This is to avoid the admin page 500-ing on production.
