### ISSUE TITLE
Add "exit button" to game

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1388]
## Task Description
Per Laura's new designs we want to add an "Exit game" button to the game screen.

## Acceptance Criteria
- [x] Button returns to Kurono dashboard when clicked.
- [x] Button respects design choices.
- [x] Logo returns to Kurono dashboard when clicked.

## Copywrite Requirements
Can be seen [here](https://miro.com/app/board/o9J_krqIYmE=/)
