### ISSUE TITLE
Publish aimmo via github actions

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/aimmo#1422]
## Task Description
Migrating from TravisCI, we need to move the publishing of the packages/images to Github actions. This means we can delete the .travis.yml config from this project.

## Acceptance Criteria
- [ ] GitHub release created
- [ ] PyPi package published
- [ ] Docker images published (aimmo-game and aimmo-game-creator)
- [ ] Semaphore notified
- [ ] Master merged into development after a release
- [ ] Travis config deleted
