### ISSUE TITLE
Create TeleportAction

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1453]
## Task Description
We want to add a TeleportAction to Kurono to help students get unstuck.

It would be used like this:

```
import random

def next_turn(world_state, avatar_state):
    new_dir = get_random_dir()

    # If the avatar cannot move, teleport
    if avatar_state.is_stuck():
        action = TeleportAction()
    else:
        action = MoveAction(new_dir)
    return action
```

The TeleportAction by itself should also have the "stuck" check so that it only teleports the user if indeed, they are stuck. Otherwise they would teleport every turn. In case the user isn't stuck but tries to teleport, a message should show up explaining why.

## Acceptance Criteria
- [ ] TeleportAction created and added to the API.
- [ ] TeleportAction teleports user to a random, inhabitable cell.
- [ ] TeleportAction only teleports user if they are stuck.
- [ ] Message (in console or as popup text) should show up if user tries to teleport but isn't stuck.

## Copywrite Requirements
- [ ] Figure out text for last requirement.

**Comment by SKairinos** [comment]
Taking aimmo offline
