### ISSUE TITLE
Create scan_nearby() function

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1465]
## Task Description
Worksheet 3 adds the ability for the avatar to scan the nearby artefacts. It returns a list of x closest artefacts (not sure if x has been defined yet).
For more info on how this function will be used, check out the Challenge 3 Teacher Guide PDF.

## Acceptance Criteria
- [ ] The number of nearest artefacts to be returned has been defined.
- [ ] Added `scan_nearby()` function to `world_state`.
- [ ] `scan_nearby()` returns a list of artefacts.

**Edge cases**:
Say x = 5.
- What if there are < 5 artefacts total on the map - we should make sure the function manages to return less than 5 artefacts.
- Imagine the function has already found the 4 closest artefacts, but there are 2 artefacts that are as far from the avatar as the other. Which one do we pick for spot 5 in the list?
