### ISSUE TITLE
Create MoveTowardsAction(artefact) action

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1466]
## Task Description
Worksheet 3 introduces a new action, `MoveTowardsAction(artefact)`. It takes in an Artefact object, and will make the Avatar move towards said Artefact.
For more info on how the action will be used, please check out the Challenge 3 Teacher Guide PDF.

## Acceptance Criteria
- [ ] `MoveTowardsAction(artefact)` added to the list of available actions.
- [ ] Action takes in an Artefact object.
- [ ] Action makes Avatar move towards the Artefact in question.
- [ ] Passing in an Artefact that does not exist should cause and print out an error, and return a `WaitAction()` instead.
- [ ] Algorithm to "move towards" artefact needs to work well (we've had discussions before about a "Path Finding algorithm", this is somewhat similar. How will the Avatar effectively move towards to the Artefact, until the point that it gets to the actual square, without getting stuck by obstacles?
