### ISSUE TITLE
Enable Worksheet 3

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1467]
## Task Description
Worksheet needs to be "enabled" in the code. This means, it needs to be marked as complete, and the Worksheet object fields need to be updated.

**N.B.**: This task should be done first **locally** so that we can test the worksheet on our machines, but we'll probably only want to push that change last so that teachers can't access an incomplete Worksheet, and so that it doesn't block us from deploying.

## Acceptance Criteria
- [ ] `thumbnail_text` field set to nothing (this marks the Worksheet as complete).
- [ ] `thumbnail_image_path` field set to `images/worksheets/lock.png`.
- [ ] `teacher_pdf_name` set to the Teacher PDF's name.
- [ ] `student_pdf_name` set to the Student PDF's name.
- [ ] `starter_code` set to the starter code mentioned in the Challenge 3 PDFs.
- [ ] These changes are done either via a migration, either via Wagtail, but need to be done on each server.
- [ ] As part of testing, please check that the map loads with the "Ancient" era skin and assets.
