### ISSUE TITLE
Administrator power - Kurono games

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/aimmo#1664]
## Task Description

Update the permissions for Kurono games and Kurono dashboard.

## Acceptance Criteria

- [x] Show all school classes in "Select class" dropdown
- [x] Add teacher name in brackets in "Select class" dropdown
- [x] Show all school games on the Games table
- [x] Add a teacher column to the Games table
- [x] Admin teacher can join the games
- [x] Admin teacher can change the worksheets - we introduced a bug that prevents either :(
- [x] Admin teacher can delete the games
- [x] When the admin teacher creates the game, the owner of the game should be the class teacher

## Copywrite Requirements

Miro

## Analytics Requirements

- [x] Add `created_by` to the Game model - this should be the `teacher_id`. Populate this with the owner for old data.
