### ISSUE TITLE
Prehistoric era with obstacles and activate worksheet 5

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1674]
## Task Description
Unlock worksheet 5 and be able to load the skin and the obstacles for the prehistoric era.

## Acceptance Criteria
- [ ] thumbnail_text field set to nothing (this marks the Worksheet as complete).
- [ ] starter_code set to the starter code mentioned in the Challenge 5 on GitBook.
- [ ] These changes are done in aimmo/worksheets.py
- [ ] Add worksheet in aimmo-game/simulation/worksheet/worksheet.py and aimmo-game/simulation/worksheet/avatar_state_serializers.py
- [ ] As part of testing, please check that the map loads with the "Prehistoric" era skin and assets.

## Analytics Requirements

**Comment by SKairinos** [comment]
Taking aimmo offline
