### ISSUE TITLE
Artefacts models and types for Prehistoric era

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1675]
## Task Description
Enable artefacts (bones) to load in worksheet 5. Types are `blue_fragment` and `red_fragment`.

## Acceptance Criteria
- [ ] The types are: `blue_fragment` and `red_fragment`
- [ ] Add artefacts to `aimmo-game/simulation/interactables/pickups/artefacts.py`
- [ ] Add models to `aimmo/static/babylon/interactables` (create a folder named `prehistoric`)
- [ ] Clean up the models in the parent folder
- [ ] Update `ARTEFACT_TYPES` in `aimmo-game-worker/simulation/world_map.py`
- [ ] Override `createInteractable` in `game_frontend/src/babylon/assetPacks/prehistoric.ts`

### Analytics Requirements
None

### Copywrite Requirements
None

**Comment by SKairinos** [comment]
Taking aimmo offline
