### ISSUE TITLE
Investigate adding teams to games

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1676]
## Task Description
Look into how to implement teams in the games and create a detailed implementation task with acceptance criteria

Ideas:
- [ ] Split the avatars into 2 teams when the game is created (red and blue team)
- [ ] The team data is temporary and doesn't need to be stored on the DB
- [ ] Add a `teams` prop to the `gameState`
- [ ] A team needs to be able to keep track of the scores and stats for that team & its members
- [ ] `get_team` needs to be made available to the `avatar_state`
- [ ] `get_teams` needs to be made available to the `world_state`

## Acceptance Criteria:
- [ ] Create the detailed implementation task
- [ ] Proof of concept pushed to a branch

**Comment by SKairinos** [comment]
Taking aimmo offline
