### ISSUE TITLE
Make avatars teleport if they pick up the wrong artefact

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1678]
## Task Description
Avatars will be teleported to a random location on the map if they pick up the wrong artefact type (the other team's artefact)

## Acceptance Criteria
- [ ] Check artefact type when picking up against the team's type 
- [ ] Teleport to a random location if wrong type
- [ ] Feedback: print in console or popup or both (Check with Laura)
- [ ] Recenter the camera on teleportation

### Copywrite Requirements
- [ ] Text for the written feedback

**Comment by SKairinos** [comment]
Taking aimmo offline
