### ISSUE TITLE
Add `CombineAction`

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1680]
## Task Description
Add `CombineAction("source_artefact_type")`

## Acceptance Criteria
- [ ] Create a `CombineAction` which takes in the name of the fragment
- [ ] Should work only if the avatar's backpack has at least 6 fragments
- [ ] If successful, remove the 6 fragments and add a bone artefact to the backpack
- [ ] If unsuccessful, print out an error message (if you have less than 6 fragments)
- [ ] Print error message if the argument doesn't match (wrong string or wrong type)
- [ ] Add Bone artefact type (no visual)

### Copywrite Requirements
- [ ] Error messages text

**Comment by SKairinos** [comment]
Taking aimmo offline
