### ISSUE TITLE
Score tracking (backend)

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1681]
## Task Description
Track scores in backend (aimmo-game (not DB))

## Acceptance Criteria
- [ ] Add `world_state.get_current_score(team_name)` which returns the team's current score
- [ ] Add `world_state.get_target_score(?team_name)` which returns the target score for the teams (check with Rebecca the formula)
- [ ] Track top 5 players with the most bones in their backpack (what happens if they have the same number? Check with Rebecca)
- [ ] Track quickest player to create a bone (from the first join turn until the turn they build the bone)
- [ ] Track time taken by each team to create all bones needed
- [ ] Time will be measured by turn numbers * 2

**Comment by SKairinos** [comment]
Taking aimmo offline
