### ISSUE TITLE
End game and show stats

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1682]
## Task Description
Show stats when both teams complete their bone goals and end the game

## Acceptance Criteria
- [ ] Check every time a Bone is created to see if the game has ended
- [ ] Display stats in scoreboard on top of map (need design)
- [ ] Disable the game (make everyone walk around randomly)
- [ ] If the game is ended and a user leaves and comes back, still show the scoreboard popup
- [ ] If the game times out, stops or the teacher changes worksheets then the game will start again and scores will be reset
- [ ] Say Game Over (check with Laura for frontend)

### Copywrite Requirements
- [ ] Design requirements

**Comment by SKairinos** [comment]
Taking aimmo offline
