### ISSUE TITLE
Stop games on worksheet change / deletion

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1785]
## Task Description
Currently, when a teacher changes the worksheet of a game or deletes a game, the Game object keeps running (this is because we don't actually delete games in the DB for stats purposes, we just make them unavailable to the user) until the 1 hour timer runs out.
This is inefficient and takes up the Agones resources for no reason.
Instead, upon worksheet change & deletion, the game should immediately be marked as stopped in order to release the associated Agones resource.

## Acceptance Criteria
- [ ] Game status is set to Stopped on worksheet change
- [ ] Game status is set to Stopped on deletion

### Analytics Requirements
- [ ] Manually check that the Agones resources get deleted properly - please document if they are not - this task is part of the optimisation of the Agones resources.
