### ISSUE TITLE
Introduce a max 15 running games constraint on the Game model

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1786]
## Task Description
The Game model does not currently have a constraint for the max amount of running games stored on the DB.
This has caused additional games to be created by teachers even when the Agones resources were already maxed out, causing those new games to never be allocated a resource.

In addition to the constraint being set, the teachers should actually be unable to create a new game when all 15 games are already running. This should be handled gracefully with proper user feedback.

## Acceptance Criteria
- [ ] Game model has a constraint of a maximum of 15 games with a running status
- [ ] If there are already 15 games running, the user should be unable to create a new game - discuss this with Laura for design implications (game creation form being disabled, etc)

### Copywrite Requirements
- [ ] To discuss with Laura
