### ISSUE TITLE
Handle edge cases of Game creation / Agones allocation gracefully

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1787]
## Task Description
Right now, when a Game is created and it fails to allocate for some reason, or it fails to change worksheet (fails to recreate) we give no feedback to the user. They get stuck in seemingly endless loading screens and dialog boxes. We need to have a graceful way of handling these which informs the user.

## Acceptance Criteria
- [ ] Have a handler for when the game fails to be allocated an Agones resource. This could be on the game loading screen - after a certain amount of time, we could give more information to the user instead of the generic "message us" message.
- [ ] Have a handler for when the worksheet fails to be updated (ie when the game fails to be recreated and allocated). Currently the code attempts to allocate the game 60 times, each attempt is 5 seconds = a wait time of 300 seconds. There might not even be an error message at the end. We should reduce the number of attempts and inform the user of the error.

### Copywrite Requirements
- [ ] Discuss design and text details with Laura

**Comment by faucomte97** [comment]
Restructure will change things
