### ISSUE TITLE
Archive Kurono 😔

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/aimmo#1875]
## Task Description
We need to archive Kurono so that we can build on it again in the future. 

## Acceptance Criteria
- [ ] Take Kurono offline
- [ ] Remove GKE from stack
- [ ] Remove Agones from stack
- [ ] Remove Terraform from stack

### Analytics Requirements
- [ ] Remove Kurono queries from Big Query

### Copywrite Requirements
- [ ] None

**Comment by lauracumming** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Code-for-Life-sprint-board-5dc58d4a85c6bd00010b8148/issues/ocadotechnology/aimmo/1875?planning-poker) with Zenhub @faucomte97 @SKairinos
