### ISSUE TITLE
Unit Testing: Pickups and general improvements

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#300]
Somewhat related to #295. But this is not just for the things in our test plan. We need more extensive unit coverage, especially for the pickups in the game. 

**_Tasks we know so far:_**

- [x] Rewrite tests for HealthPickup in `test_pickups.py`.
- [x] Add any suitable tests for `TestDamagePickup` and `TestInvulnerabilityPickup`. 
- [x] Check effect tests.
