### ISSUE TITLE
Write tests for minikube

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#425]
Write tests and improve the test coverage for the minikube infrastructure.

- [x] Create a test skeleton for future tests and reusability.
- [x] Fix dependency issues and CSRF set up.
- [x] Write initial minikube state tests.
- [x] Add custom game tests and check for services, pods and replication controllers.
- [x] Leave method declarations for the future for tests that need to be covered first.
