### ISSUE TITLE
Tutorial levels before MMO

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#478]
ex RR mockup,  less flat world
we have the level generator but we need to make sure :
- [ ] there are some tutorial levels with working example code like current prototype: RR, Less Flat World...
- [ ] teenagers know they have achieved the level (right now it's like the mmo, the avatar just stays there endlessly)
- [ ] transitions and transition videos work before levels, between levels and after the levels "before" the MMO

**Comment by j4mesholland** [comment]
We are not having tutorial levels any more
