### ISSUE TITLE
Upgrade `react-unity-webgl` to 7.x to fix Unity canvas sizing issues

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#730]
## Task Description
Currently, we have a bug where unity canvas does not resize with the window. We end up having scrollbars on our "fullscreen" web app or a big whitespace where the Unity content is meant to expand to:

![image](https://user-images.githubusercontent.com/2016308/44094960-75fba09e-9fcf-11e8-8327-75a9296ae197.png)

![image](https://user-images.githubusercontent.com/2016308/44094923-5bf6955a-9fcf-11e8-9f9e-23eb112958cf.png)

## Acceptance Criteria
- [x] Library upgraded to [7.x](https://github.com/jeffreylanters/react-unity-webgl/releases)
- [ ] Unity <-> React communication updated to work with new version (`unityContent` in redux store?)
- [x] Unity canvas resizes properly on browser resize

## Analytics Requirements
N/A

**Comment by mrniket** [comment]
Not stale
