### ISSUE TITLE
Add exit button to game screen

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#731]
## Task Description
Currently, there is no way to exit the AIMMO game screen to return to the portal.
A visual of the position an icon button style is shown below:

![x exit button](https://user-images.githubusercontent.com/18662916/44095540-fdd9f550-9fd0-11e8-961b-1d237dd6d3e5.png)

## Acceptance Criteria
- [ ] The Material design _'close'_ icon is used
- [ ] Alignment is to the right of the map nav bar
- [ ] the button closes the game screen and returns the user to the AI:MMO game page (aimmo/)
- [ ] the button is tested on staging in different browsers and laptop devices

## Analytics Requirements
- [ ] The icon is tested by at least two users outside the team for understanding and functionality (ask the user to close the game, see if the icon button is obvious to them)
