### ISSUE TITLE
App bar for AI:MMO game screen

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#737]
## Task Description
We need to implement an app bar for the game menu, UI buttons functionality and future game status

See visual for context 
![appbar](https://user-images.githubusercontent.com/18662916/44159548-af907100-a0af-11e8-9a79-8098f955e78e.png)

## Acceptance Criteria
- [x] Review app bar docs here: https://material-ui.com/demos/app-bar/
- [x] App bar background uses the secondary colour from our design system
- [x] Check any issues with drop shadow
- [x] Test on multiple devices and brwosers

## Analytics Requirements
- [ ] Test with users and get feedback on usability

**Comment by mrniket** [comment]
I'm going to combine the two Menus we have and make one AppBar

**Comment by CelineBoudier** [comment]
tested on pixel2 (!), firefox and chrome for linux
