### ISSUE TITLE
Remove ghibli movies (old obsolete example code)

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#746]
## Task Description
When we first started the React project we wrote some example code called ghiblimovies. It was supposed to be a boilerplate for our real project as we were developing it.

It's now obsolete and should be removed.

## Acceptance Criteria

- [x] Everything works fine.
- [x] No console errors.
- [x] All references removed to ghibli, including the initial state.

## Analytics Requirements

N/A
