### ISSUE TITLE
Create a `GameRunner` class

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#754]
## Task Description
This task is the create new `GameRunner` class that is responsible for fetching the game metadata from Django (currently done by the `WorkerManager`) and then lets the `WorkerManager` and `AvatarManager` know what workers and avatars need to be added/deleted.

## Acceptance Criteria
- [x] Work in task description is done
- [x] Test coverage stays the same
- [x] Docs are updated

## Analytics Requirements
N/A
