### ISSUE TITLE
Make TurnManager's only responsibility running the simulation, one turn at a time

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#755]
## Task Description
See Acceptance Criteria

## Acceptance Criteria
- [ ] TurnManager's run loop moves to GameRunner
- [ ] GameRunner will tell the GameAPI/service when a turn is finished
- [ ] GameRunner clears worker metadata after each turn
- [ ] GameRunner is the class that initializes everything to start a game (instead of service.py)
- [ ] Docs updated

## Analytics Requirements
N/A

**Comment by NiallEgan** [comment]
Has been made part of https://github.com/ocadotechnology/aimmo/issues/767.
