### ISSUE TITLE
Make changes to AI:MMO teaching materials

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#763]
## Description
**Make changes as per Rebecca's suggestions in the Review of AI:MMO teaching materials document.**

## Acceptance criteria
- [x] Make changes to InDesign files
- [x] Update code snippets and re-import into InDesign files
- [x] Create new PDF versions
- [x] Files approved by Educational Consultant

## Metrics
To see if these materials are usable in a school setting

**Comment by CelineBoudier** [comment]
Should we add "Rebecca agreeing with the materials" as a criteria?

**Comment by j4mesholland** [comment]
Yes, I've added this to the acceptance criterior now

**Comment by j4mesholland** [comment]
I have added these issues 
- #897 Update AI:MMO student challenge sheets
- #898 Update AI:MMO teacher session sheets
to reflect feedback from teachers and user testing, that we want to hide the scary imports and the use of (object). Rebecca and I also discussed changing the default code from 

```
class Avatar:
	def next_turn(self, avatar_state, world_state):
		return MoveAction(random.choice(direction.ALL_DIRECTIONS))
```

To 

``` 
class Avatar:
		return MoveAction(direction.NORTH)
```

As too much time is required in a lesson to explain the imports and changing the default code from all directions to N,S,E or W.
