### ISSUE TITLE
Separation of worker logic and simulation logic

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#767]
## Task Description
This really is a combination of https://github.com/ocadotechnology/aimmo/issues/756 and https://github.com/ocadotechnology/aimmo/issues/755, as it transpired that the two must be done together. 

## Acceptance Criteria
- [x] Create a new class named `Worker`
- [x] Move `fetch_data` from `AvatarWrapper` into `Worker`
- [x] Make `GameRunner` responsible for registering worker metadata
- [x] Rename `TurnManager` to `SimulationRunner`
- [x] Docs
- [x] TurnManager's run loop moves to GameRunner
- [x] GameRunner will tell the GameAPI/service when a turn is finished
- [x] GameRunner clears worker metadata after each turn
- [x] GameRunner is the class that initializes everything to start a game (instead of `service.py`)
- [x] Docs updated
- [x] Test coverage stays the same. 

## Analytics Requirements
N/A
