### ISSUE TITLE
Create challenges for workshop sessions

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#772]
## Task Description    
__Rebecca will create some sessions for use at the PyCon workshop.__

- Objectives
- Resources needed
- Timing
- Code examples
- Solutions

## Acceptance Criteria    

- [x] Test the sessions for usability
- [x] Check there are no bugs when executing the correct code

## Analytics Requirements
- [x] Test the sessions for usability before creating worksheets

**Comment by j4mesholland** [comment]
For review - The challenges will need to be tested as part of the review before moving on.
[Uploading... AIMMO Workshop.pdf ]

**Comment by j4mesholland** [comment]
@rdcruzCFL I have teseted out the challenges, but I had to change the import code (and later references) from __world_map__ to __world_state__ to avoid getting an error.

**Comment by rdcruzCFL** [comment]
I am confused by this, James. I had to make the opposite change. Where were you testing? I have used production and staging

**Comment by j4mesholland** [comment]
Hmm, that's odd. Are you using Staging or Production?  We are going to create a fix for this so that we can change the name without the user getting an error in the console log. I will use world_map (as this would make more sense to a user).

**Comment by NiallEgan** [comment]
For the record, I have looked in to this and either `world_map` or `world_state` should be fine.  Speaking to James, I think that the potential source of confusion is that error traceback often starts in our code rather than the user's. We have created an issue to rectify this, but in the meantime it is best to start reading the traceback from where it says `<string>`

**Comment by rdcruzCFL** [comment]
I have been through the code examples again in Research/AI:MMO workshop code to confirm that they all work.
1. generic.py (can the default code the changed to this?
```class Avatar(object):
    def handle_turn(self, world_map, avatar_state):
        from simulation.action import MoveAction
        import simulation.direction as direction	#here
        import random

        next_direction = random.choice(direction.ALL_DIRECTIONS) #here
        return MoveAction(next_direction)
```
2. random direction.py
3. random direction weighted.py
4. random direction using list.py
5. turn_around.py

All these examples use world_state but world_map seems to work as well now (production).

**Comment by j4mesholland** [comment]
We will need to create an issue to update the default code as part of this epic. It will need to to be ready, tested and on production _**before**_ PyCon on Saturday 15th
