### ISSUE TITLE
Design layout and artwork for workshop sessions

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#773]
## Task Description    
__Use approved workshop sessions to create artwork for the session sheets that will be handed out to teachers or students for each workshop.__

- Objectives
- Resources needed
- Timing
- Code examples
- Solutions

## Acceptance Criteria    

- [x] Check for spelling, punctuation and grammar
- [x] Make sure the design is clear and easy to read
- [x] The design is consistent with our brand and other teaching materials

## Analytics Requirements
- [ ] Test the sessions sheets for usability before printing multiple copies with a user

**Comment by j4mesholland** [comment]
***Please review:***
Teacher Session
[https://app.zenhub.com/files/39072690/7512ad90-1b49-4287-8935-6e8062d3d24d/download](https://app.zenhub.com/files/39072690/7512ad90-1b49-4287-8935-6e8062d3d24d/download)
Student Challenge 1
[https://app.zenhub.com/files/39072690/4217e1c1-f0de-4965-bdf9-ee3f15402bd7/download](https://app.zenhub.com/files/39072690/4217e1c1-f0de-4965-bdf9-ee3f15402bd7/download)
Student Challenge 2
[https://app.zenhub.com/files/39072690/1c355fbf-8dd4-4f37-8afe-23d84e5a217c/download](https://app.zenhub.com/files/39072690/1c355fbf-8dd4-4f37-8afe-23d84e5a217c/download)

**Comment by mariaFernando** [comment]
On Teacher Session:
- Is there any way to correct sentence/word splits like the "pdf" here?
<img width="503" alt="screen shot 2018-09-07 at 15 20 06" src="https://user-images.githubusercontent.com/30693435/45224457-eeca7000-b2b1-11e8-8e58-c4511f441dc8.png">


- There's probably a 1. missing before "Introduce"
<img width="476" alt="screen shot 2018-09-07 at 15 20 29" src="https://user-images.githubusercontent.com/30693435/45224507-0b66a800-b2b2-11e8-8895-e6fc8e601297.png">


- Small thing but the "r" on "return MoveAction(...)" isn't blue and bold
<img width="520" alt="screen shot 2018-09-07 at 15 20 48" src="https://user-images.githubusercontent.com/30693435/45224550-22a59580-b2b2-11e8-8f92-95fe1eddfdf4.png">


- I'd write "demo change the code" to keep it consistent with the other lines
<img width="459" alt="screen shot 2018-09-07 at 15 21 34" src="https://user-images.githubusercontent.com/30693435/45224597-3e10a080-b2b2-11e8-8a4c-4b1011c36c1e.png">


- Is the "..." necessary?
<img width="474" alt="screen shot 2018-09-07 at 15 22 11" src="https://user-images.githubusercontent.com/30693435/45224680-731cf300-b2b2-11e8-8a66-ac29047f7704.png">

- Confusing spacing here (?)
<img width="501" alt="screen shot 2018-09-07 at 15 22 38" src="https://user-images.githubusercontent.com/30693435/45224694-7f08b500-b2b2-11e8-9ec5-893051abd198.png">

**Comment by mariaFernando** [comment]
On Student Challenge 1:

- "Let's" instead of "Lets"
<img width="296" alt="screen shot 2018-09-07 at 15 33 51" src="https://user-images.githubusercontent.com/30693435/45225098-9f853f00-b2b3-11e8-98b1-72e44a5932d6.png">


- I'd split the first sentence into "The first five lines(...) work." and "We'll ignore them for now."
<img width="491" alt="screen shot 2018-09-07 at 15 33 58" src="https://user-images.githubusercontent.com/30693435/45225122-aca22e00-b2b3-11e8-920f-21f14e66805f.png">


- Add a comma after "The next line"
<img width="458" alt="screen shot 2018-09-07 at 15 34 04" src="https://user-images.githubusercontent.com/30693435/45225175-cc395680-b2b3-11e8-9707-9ec136e4cc99.png">


- Sounds a bit confusing, do you mean "writing"?
<img width="443" alt="screen shot 2018-09-07 at 15 34 50" src="https://user-images.githubusercontent.com/30693435/45225191-d8251880-b2b3-11e8-8b10-09c989664103.png">

**Comment by mariaFernando** [comment]
On Student Challenge 2:

- I think it should be specified the student should print the value of the variable, also in other similar cases
<img width="486" alt="screen shot 2018-09-07 at 15 38 34" src="https://user-images.githubusercontent.com/30693435/45225352-36ea9200-b2b4-11e8-9254-f859cc43ec83.png">

- "coordinates" instead of "co-ordinates" 
<img width="490" alt="screen shot 2018-09-07 at 15 39 08" src="https://user-images.githubusercontent.com/30693435/45225391-5386ca00-b2b4-11e8-8612-e2aa808a4440.png">

**Comment by j4mesholland** [comment]
I have made all those changes:

Session 1 - Teacher guidance 
[https://app.zenhub.com/files/39072690/f83135c9-1d04-4298-b791-68c6850917f0/download](https://app.zenhub.com/files/39072690/f83135c9-1d04-4298-b791-68c6850917f0/download)

Student challenge 1
[https://app.zenhub.com/files/39072690/e3e5bdb6-17f9-4bff-9e86-623eed88304a/download](https://app.zenhub.com/files/39072690/e3e5bdb6-17f9-4bff-9e86-623eed88304a/download)

Student challenge 2
[https://app.zenhub.com/files/39072690/114720b4-c365-4bc9-aa61-9e6577fb1b02/download](https://app.zenhub.com/files/39072690/114720b4-c365-4bc9-aa61-9e6577fb1b02/download)

**Comment by rdcruzCFL** [comment]
The sheets look good! I just have some minor changes, marked with asterisks:
AP–S1
Page 2 - Student Challenges
Challenge 1 (5 — 10 minutes)
1. Students change code to use random.randint() and *an* if…elif…else statement (see
Challenge Sheet 1)

AP–SC1
Footnote
2. A tuple is a data structure consisting of multiple parts
*It might be worth adding: It's rather like a list but you can't change it. 

AP–SC2
Extend your code so that your avatar turns 180° if it encounters *and* obstacle. 
Should read "an obstacle"
