### ISSUE TITLE
Upgrade Standardjs and fix linting problems

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#783]
## Task Description
Due to a misplaced config file, none of our linting for the front end was working as expected. 
This is also an opportunity to standardjs so that our linting errors are fixed with the latest standards

## Acceptance Criteria
- [x] Remove eslint
- [x] Standard upgraded to 12.x
- [x] Standard with babel-eslint is used to parse
- [x] Linting errors fixed with `standard --fix`

## Analytics Requirements
N/A
