### ISSUE TITLE
Questionnaires for PyCon user testing workshops

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#808]
## Task Description
Create questionnaires to get feedback about AI:MMO and the challenges thet have been created.
- feedback from teachers
- feedback from teenagers

## Acceptance Criteria
- [x] The questionnaires are created in Google forms
- [x] The questions cover gamplay
- [x] The questions cover the teaching materials
- [x] The questions get feedback about the UI
- [x] The questions cover uasbility in a secondary school setting
## Analytics Requirements
As we are using Google forms, we can look at the metrics after the event.

**Comment by j4mesholland** [comment]
Please review:

__Student questionnaire:__
https://docs.google.com/forms/d/e/1FAIpQLSePEjk5_EgWkCr9xqpHInSaqiyO59Iy7wCEaQXlnyIBFGKjpw/viewform?usp=sf_link

__Teacher questionnaire:__
https://docs.google.com/forms/d/e/1FAIpQLSdWIi66QtV0YHdWeUzSh2muS55yWKLOBfHDD2ylEPBWf0rbiw/viewform?usp=sf_link

**Comment by mariaFernando** [comment]
The teachers one seems fine :)

**Comment by rdcruzCFL** [comment]
**Students' version:**
- **Which school year are you in?** Could the primary option go first so they are in age order?
- **How easy are your Computer Science lessons?** They are very unlikely to be called that; they should be called Computing. Maybe add, *do you enjoy them* with a reason?
- **What do you most struggle with learning coding?** Maybe change to : *Do you have programming/coding lessons? How hard do you find them (1 - 5)? What is your favourite/least favourite thing about them?*
- **Are you taking or considering taking Computer Science or ICT as a GCSE subject?** I would remove ICT here; it is a different subject and is not really offered in the UK anymore

**Teachers**
Any chance you can change the word *coding* to *programming*?
- **Which classes / age range do you teach?** You need to be able to select more than one option here

**Comment by rdcruzCFL** [comment]
Sorry, I've closed it now but does it say "It didn't **mater**"? I'd agree though, aren't they the same?
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/10d494ff-c61f-4631-b5a5-895887c4d962)

**Comment by j4mesholland** [comment]
@mariaFernando 

_Any reason why it's 1-4 and not 1-5 or 1-3? (with uneven options they could choose an intermediate one)_

We have had feedback from people before that it's good practice to remove the middle intermediate option, as the majority of people would go for that option. I thought I'd try it for this questionnaire.

**Comment by j4mesholland** [comment]
@rdcruzCFL 

#### Students' version:

_Which school year are you in? Could the primary option go first so they are in age order?
How easy are your Computer Science lessons? They are very unlikely to be called that; they should be called Computing. Maybe add, do you enjoy them with a reason?_

**Done**


_What do you most struggle with learning coding? Maybe change to : Do you have programming/coding lessons? How hard do you find them (1 - 5)? What is your favourite/least favourite thing about them?_

**I have updated the wording, but we are asking more than one question now, so I made this into two separate questions.**

Are you taking or considering taking Computer Science or ICT as a GCSE subject? I would remove ICT here; it is a different subject and is not really offered in the UK anymore

**Done**

#### Teachers version

Any chance you can change the word coding to programming?

**Done**


Which classes / age range do you teach? You need to be able to select more than one option here

**Done**
