### ISSUE TITLE
Setup classes for PyCon user testing

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#809]
## Task Description
We need to set up classes and user logins ready for PyCon so that we can run class simulations as part of our user testing workshop.

## Acceptance Criteria
- [ ] The school and classes are already approved for use on AI:MMO
- [ ] Login cards are printed out and can be given to workshop participants
- [ ] We will need about 20 logins

## Analytics Requirements
N/A
