### ISSUE TITLE
Use semantic versioning for our PyPi packages

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#813]
## Task Description

In order to use a hotfix process and for our Pypi builds to make sense. We want to be able to use good versioning practices (PEP440 with semantic versioning)

## Acceptance Criteria

- [ ] There is a file called something like `version.txt`
- [ ] Each commit on master should be tagged with a release number coming from `version.txt`
- [ ] When travis deploys to PyPi, the script using `versioneer` should make a version on PyPi derived from the git tag

## Analytics Requirements

 N/A
