### ISSUE TITLE
Create an aimmo setup script for new starters

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#815]
### Description 
It would be nice to have a script that someone could run after cloning the aimmo repo, `./setup-aimmo` for example, that would set up & potentially install the dependencies needed to run aimmo for whoever needs it. This would not replace the manual setup instructions on the readme on github. So all the person who ran the script should then need to do is then get the aimmo-unity package and put it in the right place.

#### Minimum requirements
- [ ] Have a script that sets up the aimmo dependencies for the person using it.
- [ ] Be friendlier and more convenient than manually setting up the project.
- [ ] The script must work across platforms used by people working on the project (mac, linux/ubuntu, windows?).

#### Further requirements
- [ ] The script also fetches the packages needed in order for aimmo to run (parcel, yarn, docker etc.).
- [ ] The script gets the latest aimmo-unity package so the user doesn't need to. 

### Additional notes
The script needs to inform the person using it what it's doing. If the script fails it should also inform the user. In an ideal situation we would need only to run this script whenever someone needs to setup the project

**Comment by CelineBoudier** [comment]
let's close and open a new issue for Windows if needed
