### ISSUE TITLE
List and learn what new starters know, need to know, don't understand... about the project

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#836]
## Task Description

List
- AI:MMO architecture itself
- Kubernetes talks
etc

Learn

## Acceptance Criteria

- [x] Feel confident enough to work on AI:MMO
- [x] Know the basics of what is listed
- [x] List easy to find and share

**Comment by j4mesholland** [comment]
@dent50cent to share the list and we can review.

**Comment by dent50cent** [comment]
This is the list of information i came up with of things we knew and things we wanted to know: https://docs.google.com/document/d/1Twwi9jWNBP-VqrCMH2-leQSam5vAY2dwnu5TkB-xaZg/edit
