### ISSUE TITLE
Prepare communication to preview users

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#837]
## Task Description

Prepare a communication (email and/or terms) 
Tell them we are releasing preview version
Warn them about stuff (current known limitations, access removal....) as reviewed with legal
We need to tell them games need to have < 4 users

## Acceptance Criteria
- [ ] Email validated by a UX, a tech writer, 
- [ ] if possible legal team (see details above)
- [ ] accepted by Rebecca

**Comment by CelineBoudier** [comment]
We need to merge the two documents - Rebecca's draft and our tech writer validated one

**Comment by j4mesholland** [comment]
I have emailed @CelineBoudier and @rdcruzCFL for a review of my suggestions.
