### ISSUE TITLE
AI:MMO game page to use portal consistent navigation style

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#840]
## Task Description    
__The AI:MMO game page (https://www.codeforlife.education/aimmo/) has inconsistent navigation and logout with no easy way back to the rest of the portal.__

- This is how it looks currently:
![Current-AIMMO-game-page.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/aa193bdf-b095-44ce-90af-bcd045ec9066)

- We should add use similar top nav and subnav menus as those used on the Rapid Router game levels  page (https://www.codeforlife.education/rapidrouter/)
![RR-levels-menus.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/686757b7-837e-4e8e-8849-d74fb113fd89)

## Acceptance Criteria    
- [x] Show top menu bar for main site navigation
- [x] Student login status to be shown, with logout and password change options
- [x] Use sticky sub nav bar for game options

## Analytics Requirements
**User testing in schools**
User testing by students. Ask them to:
- [ ] Load an existing game
- [ ] Log out of the game, when finished
- [ ] Navigate to Rapid Router

**Comment by mrniket** [comment]
Closing this epic as we did this in the portal instead
