### ISSUE TITLE
Send the communication to users

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#847]
## Task Description
We need to send an email to our preview users about the preview release of AI:MMO.
If we change our terms, we need to email all our users as well regarding changes.
We need to add a link or send our teaching resources

## Acceptance Criteria

- [x] All interested and serious users have received the message 
- [x] All interested, serious users are preview users on our DB
- [x] Check with comm team about dotmailer or email manually depending...

**Comment by faucomte97** [comment]
Not stale
