### ISSUE TITLE
Updated AI:MMO game page

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#855]
## Description

__The current game landing page is inconsistent with the rest of the pages on the portal and there is no easy way back to the rest of the site.__
https://www.codeforlife.education/aimmo/

## Acceptance criteria
- [x] Use existing portal Navigation
- [x] Log in / out using existing button and options 
- [x] User must be able to join an existing game or add a new game
- [x] Links to learning resources for students
- [x] Feedback link

## Metrics
Prototypes initially, then user testing sessions.

**Comment by j4mesholland** [comment]
Please review: https://sketch.cloud/s/1xxbp/971Qdz/play
