### ISSUE TITLE
Add custom metrics for AI:MMO

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#856]
## Task Description
There is a lack of useful data about the project, an example being data regarding turn times. Therefore it would be useful to setup something that can monitor the performance of these things. The most widely used approach for this is [prometheus](), this can be set up within the cluster to process the data we want in addition to standard monitoring of our clusters, and then show it to us in a useful manner.

Useful links:
* [prometheus](https://prometheus.io/) for monitoring
* [Grafana](https://grafana.com/) for dashboards
* [Prometheus python client](https://github.com/prometheus/client_python) for creating custom metrics
* [prometheus operator](https://github.com/coreos/prometheus-operator) for implementing prometheus within kubernetes
* [example use of prometheus operator](https://coreos.com/blog/the-prometheus-operator.html)

## Acceptance Criteria
- [x] Get prometheus setup within AI:MMO
- [x] Create an "example metric" so future work has something to go on (such as measuring turn time).
- [x] Document the results of implementing this for future use.
