### ISSUE TITLE
Create Grafana deployment for prometheus

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#868]
## Task Description
Once prometheus has been set up with a least the standard cluster monitoring capabilities, we will need to create a grafana deployment in order to have a dashboard for all these metrics. An example Grafana deployment can be found in the kube-prometheus section of the [prometheus operator](https://github.com/coreos/prometheus-operator) repo.

## Acceptance Criteria
- [ ] create Grafana deployment and expose it to outside the cluster
- [ ] populate the dashboard with some relevant information (custom metrics or useful standard ones such as pod memory usage).
- [ ] Document how to add to and make use of the dashboard for all members of the project.

**Comment by CelineBoudier** [comment]
not stale
