### ISSUE TITLE
Use Docker for Local Mode

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#870]
## Task Description

Currently for local mode (i.e. without `-k`), we run everything in the same python environment as the Django application. This has two main disadvantages:

- We aren't running the game creator, game and game-workers in the same environment as we do in production
- We are tied to the python version that our Django apps use

This task is to use our docker containers for local mode.

## Acceptance Criteria

- [x] Using k8s via minikube should still work
- [x] Documentation for local mode should be updated
- [x] Should work on both macOS and Linux

## Analytics Requirements

N/A
