### ISSUE TITLE
Upgrade our docker containers to python 3

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#871]
## Task Description

This task is to upgrade our docker containers from python:2-alpine to python:3-alpine.
Our code base should be fairly python 3 compatible apart from any breaking changes we couldn't fix in python 2.7.
We would also need to make sure our tests run in their respective docker containers.

## Acceptance Criteria

- [x] Docker base images changed from `python:2-alpine` to `python:3-alpine`
- [x] Pipfile and Pipfile.lock are updated
- [x] Fix any errors in our code that arise from upgrading to python 3

## Analytics Requirements

N/A

**Comment by dent50cent** [comment]
Dockerfiles are now using Python 3. However, none of the workers is being created anymore and the games aren't giving any errors, all you get is the game creator giving a NewConnectionError when trying to list the games (which are being created).

Game pods don't get any further than `self.api = kubernetes.client.CoreV1Api()` on line 20 in the `kubernetes_worker_manger.py`, if you print something before and after this line only the first thing will be printed.
