### ISSUE TITLE
Hide all approved/necessary imports from the avatar code

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#887]
## Task Description
We need to pre-import necessary elements that the users can use in their avatar code
That will mean also changing the documents / UX of how to code an avatar

## Acceptance Criteria

- [x] All the necessary imports are done on our side and the code works when we try to use our pickups, actions etc
- [x] The default code changes to reflect that
- [x] We have ex. code test cases to prove it works
- [x] We update our teaching documents
- [x] We need to think more about the new UX / how to tell people about the impots etc
