### ISSUE TITLE
Create a banner for the new terms

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#917]
## Task Description

We need a banner for a few weeks to warn our users that we have changed our terms and conditions.
Ex of wording: We have updated our terms, you can click  here to review them, ...

## Acceptance Criteria

- [ ] wording accepted by James and Rebecca
- [ ] banner can be seen when you go on the website 
- [ ] banner either disappears when you click or isn't too prominent

**Comment by CelineBoudier** [comment]
Issue moved to [ocadotechnology/codeforlife-portal #847](https://github.com/ocadotechnology/codeforlife-portal/issues/847) via [**ZenHub**](https://www.zenhub.com/)
