### ISSUE TITLE
Run code button: different states

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#922]
## Task Description

code button, different states:
run
loading
success

## Acceptance Criteria
- [ ] designs accepted for each state
- [ ] designs shown in context and accepted in context
- [ ] buttons implemented and working for the different states

## Analytics Requirements

**Comment by j4mesholland** [comment]
Designs for states below:

**Run code state** default
![Run-code.jpg](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/4f1cc1a9-1918-4523-8fd4-83d1faca0c31)


**Updating state** for as long as the code takes to run

![Updating.jpg](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/7bd6d24d-be73-4577-b31e-45e04718f584)

**Done state** show for 4 seconds when the code has updated

![Done.jpg](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/01cb62d2-ad15-4a4c-9956-6cabf25e3ab9)

**Comment by j4mesholland** [comment]
And an error state with optional snack bar notification:

![Error.jpg](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/8de54ff9-c43a-4ece-a7fa-3220508568e8)
