### ISSUE TITLE
Add console app bar

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#926]
## Task Description
User testing has shown that players are confused by the lack of any heading or clear division between the code editor and the console.

## Acceptance Criteria
- [x] **Size:** 40px hight, auto width
- [x] **Icon:** Use the console icon in the inactive state
- [x] **Colour:** Surface 800 (grey)
- [ ] **Text:** Body 1, medium emphasis

***Stretch Goal***
- Add clear console functionality and button

## Analytics Requirements
- Test at different screen sizes and OS.
***Stretch Goal***
- Test clear console functionality

**Comment by j4mesholland** [comment]
**Console log app bar**
![Dark.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/feac06d9-719a-44b1-acd9-f75d27839b15)

**UI for context**
![Run-code.jpg](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/60b1e21c-e2d9-4fec-a471-3b3da88cb881)
