### ISSUE TITLE
Create "Are we running out of resources?" dashboard

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#956]
## Task Description

A dashboard that should give us the information to answer the question "Are we running out of resources?" and other scalability questions.

## Acceptance Criteria

A dashboard configuration on dev, staging and production that has:
- [x] Total cluster CPU, Memory use
- [x] Total cluster network use
- [x] Number of Games running
- [x] Number of Workers running
- [x] The highest number of workers a game has

## Analytics Requirements

See the acceptance criteria
