### ISSUE TITLE
Persist grafana

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#961]
## Task Description
Persist grafana so that all of our configurations do not get lost on pod shutdown.

## Acceptance Criteria
- [x] Authentication is persisted through reboots
- [x] Dashboard configuration is persisted through reboots
- [x] Points 1 and 2 work on dev
- [ ] Points 1 and 2 work on staging (after review)
- [ ] Points 1 and 2 work on production (after QA)

## Analytics Requirements

N/A
