### ISSUE TITLE
Unprovision Cluster Overview dashboard

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#976]
## Task Description
Now that we have our dashboards persisted on a database, we would like to unprovision it so that we can make changes to it using the grafana UI

## Acceptance Criteria
- [x] The Cluster Overview dashboard is the same as it was before the task
- [x] We are able to make changes to the dashboard using the Grafana UI
- [x] The changes are persisted on the database

## Analytics Requirements
N/A
